config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  resources :cards do
    get :check, on: :member
  end
  resources :users
  resources :sessions
  resources :decks do
    get :make_current, on: :member
  end
  

end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  skip_before_action :require_login, only: [:index]

  def index
    return unless current_user

    @user = User.find(current_user.id)
    @random_card = @user.card_for_check
  end
end

app/views/home/index.html.erb
<h1 class="display-4"><%= "#{I18n.t('home_controller.index.greeting.p1')} #{I18n.t('logo')}" %></h1>
<p class="lead"><%= I18n.t('home_controller.index.greeting.p2') %></p>
<hr class="my-4">
<% if current_user %>
  <div class="card text-center center_div" style="width: 400px; margin: auto;" >
    <div class="card-body">
      <% if @random_card %>
        <%= show_cards_image(@random_card) %>
        <h5 class="card-title"><h3><%= @random_card.translated_text %></h3></h5>
        <%= simple_form_for :check_data, url: check_card_path(@random_card), method: :get do |f| %>
            <%= f.input :translation, label: false, required: false %>
            <%= f.button :submit, class: 'btn btn-primary' %>
        <% end %>
        <h6 class="card-subtitle mb-2 text-muted"><%= @random_card.review_date.strftime("%d/%m/%Y") %></h6>
      <% else %>
        <h4><%= I18n.t('home_controller.index.end_message') %></h4>
      <% end %>
    </div>
  </div>
<% else %>
  <%= render template: 'sessions/new' %>
<% end %>