config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  resources :cards do
    get :check, on: :member
  end
  resources :users
  resources :sessions
  resources :decks do
    get :make_current, on: :member
  end
  

end

app/models/card.rb
# frozen_string_literal: true

require 'damerau-levenshtein'

class Card < ApplicationRecord
  TIME_INTERVALS = [0, 1, 3, 7, 14, 28].freeze

  belongs_to :user
  has_and_belongs_to_many :decks

  validates :original_text, presence: true, length: { maximum: 20 }
  validates :translated_text, presence: true, length: { maximum: 50 }
  validate :texts_not_equal
  validate :one_deck_at_least?

  scope :ready, -> { where('review_date <= ?', Date.today) }

  before_create -> { self.review_date = Date.today }

  mount_uploader :image, CardImageUploader

  def one_deck_at_least?
    errors.add(:decks, 'need one deck at least') if decks.empty?
  end

  def self.random
    order(Arel.sql('RANDOM()')).first
  end

  # Updates card's check_distance to figure out is translation right or wrong
  def check_translation(translation)
    # Initialize Damerau-Levenshtein algo handler
    dl = DamerauLevenshtein
    # Check is successfull if DL distance eq or more than two
    check_distance(dl.distance(original_text, translation))
    if check_distance <= 2
      # Increase successfull_attempts counter
      evaluate_successfull_attempt
      update_card_date
    else
      # Increase failed_attempts counter
      self.failed_attempts += 1
      # Update card date if there are 3 failures
      update_card_date if failures_strike?
    end
  end

  def texts_not_equal
    if original_text.downcase.strip == translated_text.downcase.strip
      errors.add(:translated_text, I18n.t('card.errors.translation_error'))
    end
  end

  def check_distance(data = nil)
    data ? @check_distance = data : @check_distance
  end

  private

  def evaluate_successfull_attempt
    # Increase successfull attempts counter
    self.successfull_attempts += 1
    # Reset failures counter
    self.failed_attempts = 0
    # successfull_attempts remains at maximum value if its exceed it
    # to correspond maximal time interval
    self.successfull_attempts = 5 if self.successfull_attempts > 5
  end

  def failures_strike?
    # if counter reaches value of 3
    false if self.failed_attempts <= 3
    # failed_attempts remains at maximum value if its exceed it
    self.failed_attempts = 3
    # change time interval to the corresponding 1 succesful attempt
    self.successfull_attempts = 1
    true
  end

  # Update card date according to the counters
  # Each value of successfull_attempts counter correspond to specific time interval
  def update_card_date
    update!(review_date: Date.today + TIME_INTERVALS[self.successfull_attempts])
  end
end

app/controllers/cards_controller.rb
# frozen_string_literal: true

class CardsController < ApplicationController
  before_action :find_card, only: %i[update edit check show destroy]

  def index
    @cards = current_user.cards
  end

  def new
    @card = Card.new
  end

  def create
    @card = current_user.cards.build(card_params)
    if @card.save
      flash[:success] = I18n.t('card.flashes.successfull.create')
      redirect_to new_card_url
    else
      # Simple form automatically flashes about failing validation
      # and it need render to throw a hint
      render 'new'
    end
  end

  def update
    if @card.update(card_params)
      flash[:success] = I18n.t('card.flashes.successfull.update')
      redirect_to cards_url
    else
      render 'edit'
    end
  end

  def check
    translation = params[:check_data][:translation]
    @card.check_translation(translation)
    if @card.check_distance.zero?
      flash[:success] = I18n.t('card.flashes.successfull.check')
    elsif @card.check_distance <= 2
      flash[:success] = I18n.t('card.check.almost')
      flash[:notice] = "#{I18n.t('card.check.right_transl')}: #{@card.original_text}.
                        #{I18n.t('card.check.you_wrote')}: #{translation}."
    else
      flash[:danger] = I18n.t('card.flashes.unsuccessfull.check')
    end
    redirect_to root_url
  end

  def show; end

  def edit; end

  def destroy
    @card.destroy
    flash[:success] = I18n.t('card.flashes.successfull.destroy')
    redirect_to cards_url
  end

  private

  def card_params
    params.require(:card).permit(:original_text, :transcription, :translated_text,
                                 :review_date, :image, :remove_image, deck_ids: [])
  end

  def find_card
    @card = current_user.cards.find(params[:id])
  end
end

app/views/cards/_card.html.erb
<a href= <%= card_path(card) %> class="custom-card">
  <div class="card text-center" >
    <div class="card-body">
      <%= render partial: 'cards/card_content', locals: {card: card} %>
    </div>
  </div>
</a>

app/views/cards/_card_content.html.erb
<%= image_tag(card.image.url, class: "card-image") if card.image? %>
<h5 class="card-title"><h3><%= card.original_text %></h3></h5>
<h6 class="card-subtitle mb-2 text-muted"><%= card.transcription %></h6>
<p class="card-text"><%= card.translated_text %></p>
<h6 class="card-subtitle mb-2 text-muted"><%= card.review_date.strftime("%d/%m/%Y") %></h6>

app/views/cards/_content.html.erb
<div class="card text-center" >
  <div class="card-body">
    <%= show_cards_image(card) %>
    <h5 class="card-title"><h3><%= card.original_text %></h3></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= card.transcription %></h6>
    <p class="card-text"><%= card.translated_text %></p>
    <h6 class="card-subtitle mb-2 text-muted"><%= card.review_date.strftime("%d/%m/%Y") %></h6>
  </div>
</div>

app/views/cards/_form.html.erb
<div class="container center_div" style= "width: 400px">
  <%= simple_form_for @card, html: { multipart: true } do |f| %>
    <%= f.input :original_text, input_html: { maxlength: 20 } %>
    <%= f.input :translated_text, input_html: { maxlength: 50 } %>
    <%= f.input :transcription, input_html: { maxlength: 50 }, required: false %>
    <%= f.association :decks, collection: current_user.decks, include_blank: true, as: :check_boxes %>
    <%= f.label :image, required: false %>
    <%= f.file_field :image, required: false %>
    <%= f.input :remove_image, as: :boolean if @card.image.file %>
    <%= f.button :submit, class: 'btn btn-primary btn-space' %>
  <% end %>
</div>

app/views/cards/edit.html.erb
<h1><%= I18n.t('cards_controller.update_title') %></h1>
<%= render partial: 'form' %>

app/views/cards/index.html.erb
<h1><%= I18n.t('cards_controller.index_title') %></h1>
<div class="container">
  <div class="card-columns">
    <%= render @cards %>
  </div>
</div>

app/views/cards/new.html.erb
<h1><%= I18n.t('cards_controller.new_title') %></h1>
<%= render partial: 'form' %>

app/views/cards/show.html.erb
<div class="container center_div" style= "width: 400px">
<div class="card" >
  <div class="card-body">
    <%= render partial: 'card_content', locals: {card: @card} %>
    <div class="card-footer">
      <div class="btn-group">

          <%= button_to I18n.t('cards_controller.show.edit'), edit_card_path(@card), method: :get, class: 'btn btn-primary'  %>


          <%= button_to I18n.t('cards_controller.show.delete'), card_path(@card), method: :delete, class: 'btn btn-primary' %>

      </div>
    </div>

  </div>
</div>
</div>