config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  resources :cards do
    get :check, on: :member
  end
  resources :users
  resources :sessions
  resources :decks do
    get :make_current, on: :member
  end
  

end

app/models/deck.rb
# frozen_string_literal: true

class Deck < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :cards

  validates :name, presence: true, length: { maximum: 20 },
                   uniqueness: { case_sensitive: true, scope: :user_id }
  validates :user, presence: true

  def current?
    id == user.current_deck.id
  end
end

app/controllers/decks_controller.rb
# frozen_string_literal: true

class DecksController < ApplicationController
  before_action :find_deck, only: %i[show update edit make_current destroy]

  def index
    @decks = current_user.decks
  end
  
  def show
    @cards = @deck.cards
  end
  
  def new
    @deck = Deck.new
  end
  
  def create
    @deck = current_user.decks.build(deck_params)
    @deck.user_id = current_user.id
    if @deck.save
      flash[:success] = I18n.t('deck.flashes.successfull.create')
      redirect_to decks_path
    else
      render 'new'
    end
  end
  
  def update
    if @deck.update(deck_params)
      flash[:success] = I18n.t('deck.flashes.successfull.update')
      redirect_to decks_path
    else
      render 'edit'
    end
  end
  
  def destroy
    return if @deck.current?
    @deck.destroy
    flash[:success] = I18n.t('deck.flashes.successfull.destroy')
    redirect_to decks_path
  end
  
  def make_current
    current_user.update!(current_deck: @deck)
    redirect_to decks_path
  end
  
  def edit; end
  
  private
  
  def find_deck
    @deck = current_user.decks.find(params[:id])
  end

  def deck_params
    params.require(:deck).permit(:name)
  end
end

app/views/decks/_deck.html.erb
<div class="custom-card" > 
  <div class="card text-center" >
    <div class="card-body">
      <h5 class="card-title"><h3><%= link_to deck.name, deck_path(deck) %></h3></h5>
      <p class="card-text"><%= "#{I18n.t('decks_controller.count')}: #{deck.cards.count}" %></p>
      <% if deck.current? %>
        <h6 class="card-subtitle mb-2 text-muted"><%= I18n.t('decks_controller.already_current') %></h6>
      <% else %>
        <%= button_to I18n.t('decks_controller.make_current'), make_current_deck_path(deck), method: :get, class: 'btn btn-primary'  %>
        <%= button_to I18n.t('decks_controller.update'), edit_deck_path(deck), method: :get, class: 'btn btn-primary' %>
        <%= button_to I18n.t('decks_controller.delete'), deck_path(deck), method: :delete, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/decks/_form.html.erb
<div class="container center_div" style= "width: 400px">
  <%= simple_form_for @deck do |f| %>
    <%= f.input :name, input_html: { maxlength: 20 }, required: false %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/decks/edit.html.erb
<h1><%= I18n.t('deck.rename') %></h1>
<%= render partial: 'form' %>

app/views/decks/index.html.erb
<h1><%= I18n.t('decks_controller.index_title') %></h1>
<div class="container">
  <div class="card-columns">
    <%= render @decks %>
  </div>
</div>

app/views/decks/new.html.erb
<h1><%= I18n.t('header.create_deck') %></h1>
<%= render partial: 'form' %>

app/views/decks/show.html.erb
<h1><%= "#{@deck.name} Deck" %></h1>
<div class="container">
  <div class="card-columns">
    <%= render partial: "cards/card", collection: @cards %>
  </div>
</div>