config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  resources :cards do
    get :check, on: :member
  end
  resources :users
  resources :sessions
  resources :decks do
    get :make_current, on: :member
  end
  

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg" style="background-color: #772064;">
  <div class="container">
    <%= link_to I18n.t('logo'), root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <ul class="navbar-nav ml-auto">
      
      <li class="nav-item">
        <% unless current_user %>
          <% if I18n.locale == I18n.default_locale %>
            <%= link_to I18n.t('header.russian'), { :locale=>'ru' }, class:"nav-link" %>
          <% else %>
            <%= link_to I18n.t('header.english'), { :locale=>'en' }, class:"nav-link" %>
          <% end %>
        <% end %>
      </li>
      
      <% if current_user %>
        <li class="nav-link">
          <%= current_user.email %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= I18n.t('header.cards') %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to I18n.t('header.add_card'), new_card_path, class: "dropdown-item" %>
            <%= link_to I18n.t('header.all_cards'), cards_path, class: "dropdown-item" %>
          </div>
        </li>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= I18n.t('header.decks') %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to I18n.t('header.create_deck'), new_deck_path, class: "dropdown-item" %>
            <%= link_to I18n.t('header.all_decks'), decks_path, class: "dropdown-item" %>
          </div>
        </li>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= I18n.t('header.account') %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to I18n.t('header.settings'), edit_user_path(current_user), class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to I18n.t('header.log_out'), logout_path, method: :get, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>
      
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<head>
  <meta charset="utf-8">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
    <!-- Navigation -->
    <%= render 'layouts/header' %>
    <!-- Page Content -->
    <div class="container">
      <!-- Messages -->
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <div class="jumbotron text-center">
        <%= yield %>
      </div>
      <%= debug(params) if Rails.env.development? %>
    </div>
</body>